**welcome to numpy tutorial**


In [2]:
import numpy as np

In [3]:
myarr = np.array([[3,6,32,64]], np.int64)

In [4]:
myarr[0,1]

np.int64(6)

In [5]:
myarr . shape

(1, 4)

In [6]:
myarr . dtype

dtype('int64')

In [7]:
myarr[0,1]

np.int64(6)

myarr[0,1] = 45

In [8]:
myarr

array([[ 3,  6, 32, 64]])

# array creation : conversion from other python structure

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,5]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 5]])

In [11]:
listarray . shape


(3, 3)

In [12]:
listarray .dtype

dtype('int64')

In [13]:
listarray .size

9

In [14]:
np . array({3,4,5})

array({3, 4, 5}, dtype=object)

# intrinsic numpy array

In [15]:
zeros = np.zeros ((2,10))

In [16]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
zeros .dtype

dtype('float64')

# range

In [18]:
ra = np . arange(20)


In [19]:
ra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# equally length space

In [20]:
lspace = np . linspace(1,3,10)

In [21]:
lspace

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

# empty

In [22]:
emp = np . empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810336e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        1.69118108e-306, 7.56599128e-307, 1.42410974e-306]])

# emptylikes

In [24]:
emp_likes = np . empty_like(lspace)

In [25]:
emp_likes

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

# identity

In [26]:
iden = np. identity(45)


In [27]:
iden

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [28]:
# Numpy axis

In [29]:
import numpy as np

In [30]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [31]:
arr = np.array(x)

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.shape


(3, 3)

In [34]:
arr.sum(axis=0)

array([12, 15, 18])

In [35]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [36]:
arr.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
arr.flat

In [38]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [39]:
arr.ndim

2

In [40]:
arr.size

9

In [41]:
arr.nbytes

72

In [42]:
one=np.array([1,6,0,678373])

In [43]:
one.argmax()

np.int64(3)

In [44]:
one.argmin()

np.int64(2)

In [45]:
one.argsort()

array([2, 0, 1, 3])

In [46]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [47]:
arr.argmin()

np.int64(0)

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.argmax()

np.int64(8)

In [50]:
arr.argmax(axis=1)

array([2, 2, 2])

In [51]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2=np.array([[1, 2, 1],
       [4, 0, 6],
       [7, 1, 0]])

In [56]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [14,  9,  9]])

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2

array([[1, 2, 1],
       [4, 0, 6],
       [7, 1, 0]])

In [59]:
arr*arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [49,  8,  0]])

In [60]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [61]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [63]:
arr.sum()

np.int64(45)

In [64]:
arr.max()

np.int64(9)

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.where (arr>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [67]:
type(np.where (arr>5))

tuple

In [68]:
np.count_nonzero(arr)

9

In [69]:
arr[1,2]=0

In [70]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [71]:
arr

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

In [72]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [73]:
x=np.nonzero(arr)

In [74]:
x

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [78]:
np.transpose(x)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 1],
       [2, 2]])